# Generated by Django 4.1.5 on 2023-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(default='a', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(default='a', max_length=3),
            preserve_default=False,
        ),
    ]
