# Generated by Django 4.1.5 on 2023-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
